# Sample Prometheus config

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'Odpytywacz Windows'
    static_configs:
      - targets: [ '192.168.100.120:9182' ]
  - job_name: 'Odpytywacz Linux - MySQL'
    static_configs:
      - targets: ['192.168.100.120:9104']
        labels:
          alias: odpytywacz-mysql
  - job_name: 'Odpytywacz Linux - Mongo'
    static_configs:
      - targets: ['192.168.100.120:9001']
        labels:
          alias: odpytywacz-mongo
  - job_name: 'Odpytywacz Linux - Python App'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.100.120:5000']
        labels:
          alias: odpytywacz-python-app
