# Sample Prometheus config

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'Odpytywacz Windows'
    static_configs:
      - targets: [ '192.168.100.120:9182' ]
  - job_name: 'Odpytywacz Linux'
    static_configs:
      - targets: ['192.168.100.120:9104']
        labels:
          alias: odpytywacz
